### ISSUE TITLE
error: __vite_ssr_import_1__.default is not a function

### ISSUE THREAD

**Issue by dcsan** [poppa/sveltekit-svg#63]
I'm getting the errors below on trying to import an icon using 

```sh
@poppanator/sveltekit-svg": "^4.2.1",
"@sveltejs/kit": "^2.0.0",
```

and vite.config like:

```sh
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';
import svg from '@poppanator/sveltekit-svg';

export default defineConfig({
	plugins: [sveltekit(), svg()]
});
```

```sh
10:57:06 PM [vite] hmr update /src/routes/bmc/dynamic/+page.svelte, /src/app.pcss (x3)
10:57:14 PM [vite] hmr update /src/routes/bmc/dynamic/+page.svelte, /src/app.pcss (x4)
data /src/routes/bmc/dynamic/bmc.svg?component
TypeError: __vite_ssr_import_1__.default is not a function
    at _page (/Users/dc/dev/proj/fingraph/app/src/routes/bmc/dynamic/+page.svelte:28:31)
    at children (/Users/dc/dev/proj/fingraph/app/.svelte-kit/generated/root.svelte:94:6)
    at _layout (/Users/dc/dev/proj/fingraph/app/src/routes/+layout.svelte:11:12)
    at Root (/Users/dc/dev/proj/fingraph/app/.svelte-kit/generated/root.svelte:65:3)
    at Module.render (/Users/dc/dev/proj/fingraph/app/node_modules/.pnpm/svelte@5.0.0-next.241/node_modules/svelte/src/internal/server/index.js:115:2)
    at Function._render [as render] (/Users/dc/dev/proj/fingraph/app/node_modules/.pnpm/svelte@5.0.0-next.241/node_modules/svelte/src/legacy/legacy-server.js:27:18)
    at Module.render_response (/Users/dc/dev/proj/fingraph/app/node_modules/.pnpm/@sveltejs+kit@2.5.25_@sveltejs+vite-plugin-svelte@4.0.0-next.6_svelte@5.0.0-next.241_vite@5.4_wlrc23kwklmhveysmbym2vkorm/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:171:29)
    at async Module.render_page (/Users/dc/dev/proj/fingraph/app/node_modules/.pnpm/@sveltejs+kit@2.5.25_@sveltejs+vite-plugin-svelte@4.0.0-next.6_svelte@5.0.0-next.241_vite@5.4_wlrc23kwklmhveysmbym2vkorm/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:286:10)
    at async resolve (/Users/dc/dev/proj/fingraph/app/node_modules/.pnpm/@sveltejs+kit@2.5.25_@sveltejs+vite-plugin-svelte@4.0.0-next.6_svelte@5.0.0-next.241_vite@5.4_wlrc23kwklmhveysmbym2vkorm/node_modules/@sveltejs/kit/src/runtime/server/respond.js:449:18)
    at async Module.respond (/Users/dc/dev/proj/fingraph/app/node_modules/.pnpm/@sveltejs+kit@2.5.25_@sveltejs+vite-plugin-svelte@4.0.0-next.6_svelte@5.0.0-next.241_vite@5.4_wlrc23kwklmhveysmbym2vkorm/node_modules/@sveltejs/kit/src/runtime/server/respond.js:322:20)

```

**Comment by poppa** [comment]
It's probably of more interest to see the code where the import is done, e.g. `app/src/routes/bmc/dynamic/+page.svelte:28:31`

**Comment by dcsan** [comment]
actually got it to work, thanks!
